main: ${mainClass}
version: ${version}
name: ${name}
api-version: ${api-version}
author: ${author}
description: ${description}
commands:
  particleapi:
    description: Main command
    aliases: [particle, papi]
    usage: /particleapi <subcomando>